const GET_ALL_USER_INFO_REQUEST = 'user/GET_ALL_USER_INFO_REQUEST';
const GET_ALL_USER_INFO_REQUEST_SUCCESS = 'user/GET_ALL_USER_INFO_REQUEST_SUCCESS';
const GET_ALL_USER_INFO_REQUEST_FAILURE = 'user/GET_ALL_USER_INFO_REQUEST_FAILURE';
const login = 'login';

export {
    GET_ALL_USER_INFO_REQUEST,
    GET_ALL_USER_INFO_REQUEST_SUCCESS,
    GET_ALL_USER_INFO_REQUEST_FAILURE,
    login,
};