export default {
    FONT_SIZE_PRE_SMALL: 11,
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_SEMI__SMALL: 13,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_SEMI_MEDIUM: 15,
    FONT_SIZE_LARGE: 16,
    FONT_SIZE_SEMI_LARGE: 20,
    FONT_SIZE_BIG: 22,
    FONT_WEIGHT_LIGHT: "300",
    FONT_WEIGHT_MEDIUM: "500",
    FONT_WEIGHT_REGULAR : "400",
    FONT_WEIGHT_THIN : "100",
    FONT_WEIGHT_ULTRA_LIGHT : "200",
    FONT_WEIGHT_SEMIBOLD : "600",
    FONT_WEIGHT_BOLD : "700",
    FONT_WEIGHT_HEAVY : "800",
    FONT_WEIGHT_BLACK : "900",
    FONT_FAMILY : 'Cairo'

  };
