const CLEAR_NOTES = 'NOTES/CLEAR_NOTES';
const NOTES_FAIL = 'NOTES/NOTES_FAIL';
const PENDING_REQUEST_NOTES = 'NOTES/PENDING_REQUEST_NOTES';
const SUCCESS_REQUEST_NOTES = 'NOTES/SUCCESS_REQUEST_NOTES';
const PENDING_DELETE_NOTES = 'NOTES/PENDING_DELETE_NOTES';
const SUCCESS_DELETE_NOTES = 'NOTES/SUCCESS_DELETE_NOTES';

export {
  CLEAR_NOTES,
  PENDING_REQUEST_NOTES,
  SUCCESS_REQUEST_NOTES,
  PENDING_DELETE_NOTES,
  SUCCESS_DELETE_NOTES,
  NOTES_FAIL,
};
