const CLEAR_NOTES = 'NOTES/CLEAR_NOTES';
const NOTES_FAIL = 'NOTES/NOTES_FAIL';
const PENDING_REQUEST_NOTES = 'NOTES/PENDING_REQUEST_NOTES';
const SUCCESS_REQUEST_NOTES = 'NOTES/SUCCESS_REQUEST_NOTES';
const PENDING_DELETE_NOTES = 'NOTES/PENDING_DELETE_NOTES';
const SUCCESS_DELETE_NOTES = 'NOTES/SUCCESS_DELETE_NOTES';

const CLEAR_BOOKS_NOTES = 'NOTES/CLEAR_BOOKS_NOTES';
const BOOKS_NOTES_FAIL = 'NOTES/BOOKS_NOTES_FAIL';
const PENDING_REQUEST_BOOKS_NOTES = 'NOTES/PENDING_REQUEST_BOOKS_NOTES';
const SUCCESS_REQUEST_BOOKS_NOTES = 'NOTES/SUCCESS_REQUEST_BOOKS_NOTES';
const PENDING_DELETE_BOOKS_NOTES = 'NOTES/PENDING_DELETE_BOOKS_NOTES';
const SUCCESS_DELETE_BOOKS_NOTES = 'NOTES/SUCCESS_DELETE_BOOKS_NOTES';



export {
  CLEAR_NOTES,
  PENDING_REQUEST_NOTES,
  SUCCESS_REQUEST_NOTES,
  PENDING_DELETE_NOTES,
  SUCCESS_DELETE_NOTES,

  CLEAR_BOOKS_NOTES,
  BOOKS_NOTES_FAIL,
  PENDING_REQUEST_BOOKS_NOTES,
  SUCCESS_REQUEST_BOOKS_NOTES,
  PENDING_DELETE_BOOKS_NOTES,
  SUCCESS_DELETE_BOOKS_NOTES,
  NOTES_FAIL,
};
